version: "2"

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: prestashop
    ports:
      - 33060:3306

  prestashop:
    build: .
    links:
      - mysql
    ports:
        - 8787:80
    environment:
      DB_SERVER: mysql # Use MySQL image
      PS_DEV_MODE: 1
      PS_INSTALL_AUTO: 1
      PS_DOMAIN: localhost:8787
      PS_LANGUAGE: es
      PS_COUNTRY: co
      PS_FOLDER_ADMIN: adminstore
      PS_FOLDER_INSTALL: xinstall
      PS_HANDLE_DYNAMIC_DOMAIN: 1
      ADMIN_MAIL: demo@prestashop.com
      ADMIN_PASSWD: prestashop_demo
    depends_on:
      - mysql