version: "3.2"

services:
  database:
    container_name: plugin_ps_database
    image: mysql:${MYSQL_VERSION:-5.7}
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: prestashop
    ports:
      - ${MYSQL_PORT:-33060}:3306

  prestashop:
    container_name: plugin_ps_prestashop
    image: prestashop/prestashop:${PS_VERSION:-1.6}
    links:
      - database
    ports:
      - ${WEB_PORT:-8787}:80
    volumes:
      - .:/var/www/html/modules/placetopaypayment
    environment:
      DB_SERVER: database
      PS_DEV_MODE: 1
      PS_INSTALL_AUTO: 1
      PS_DOMAIN: localhost:${WEB_PORT:-8787}
      PS_FOLDER_ADMIN: adminstore
      PS_FOLDER_INSTALL: xinstall
      PS_HANDLE_DYNAMIC_DOMAIN: 1
      ADMIN_MAIL: demo@prestashop.com
      ADMIN_PASSWD: prestashop_demo
    depends_on:
      - database
